[build]
command = "node server.js" # or specify the command that runs server.js
publish = "." # No need to publish a build folder for a backend



[[redirects]]
  from = "/*"
  
  status = 200
  force = true

